"""
Django settings for adbizWebAPI project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import yaml

from .common.utils import ClsDbConfig

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Setup DB Connection parameters
_DB_SERVER_NAME = ""
_DB_USER_NAME = ""
_DB_PASSWORD = ""
_DB_PORT = ""
_DB_CONFIG_FILE = ""
_DB_DATABASE_NAME = ""

_DB_CONFIG_FILE = str(os.path.join(os.path.sep, BASE_DIR, 'adbizWebAPI','config', 'db.yaml'))
print(_DB_CONFIG_FILE)

try:
    with open(_DB_CONFIG_FILE,"r") as f:
        config_items = yaml.full_load(f)
        for items, v in config_items.items():                        
            if items=='mysql':                            
                _DB_SERVER_NAME = v["server"]                           
                _DB_USER_NAME = v["user"]
                _DB_PASSWORD = v["password"]
                _DB_PORT = v["port"] 
                _DB_DATABASE_NAME = v["database"]
except Exception as e:
    print("Error!! Error in reading Database config file...", _DB_CONFIG_FILE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ymq0cn)_3nh=^)q5m7f#r90-*szv6eod%t2_r+36eb5=(h^8d$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'adbizWebAppAuth',
    'adbizProductEngine',
    # 'django_revision.apps.AppConfig',
    # 'django_audit_fields.apps.AppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'audit_log.middleware.UserLoggingMiddleware',

]

ROOT_URLCONF = 'adbizWebAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['adbizWebAPI/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adbizWebAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'USER': _DB_USER_NAME,
        'PASSWORD': _DB_PASSWORD,
        'HOST': _DB_SERVER_NAME,
        'PORT': _DB_PORT,
        'NAME': _DB_DATABASE_NAME,        
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
#--------------------------------------------------
STATIC_ROOT = os.path.join(BASE_DIR, 'root')
print(STATIC_ROOT)

#-----------------------------------------------------
STATICFILES_DIRS = [
        os.path.join(BASE_DIR, '/home/setupadmin/adbiz/components/Web/api/adbizWebAPI/ui/veltrix'),
]
