# Generated by Django 3.0.5 on 2020-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbizroles',
            name='role_reference_id',
        ),
        migrations.AddField(
            model_name='adbizroles',
            name='is_module_admin',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Module Admin?'),
        ),
        migrations.AddField(
            model_name='adbizroles',
            name='is_service_account',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is a Service Account?'),
        ),
        migrations.AddField(
            model_name='adbizroles',
            name='system_role_reference',
            field=models.CharField(max_length=255, null=True, verbose_name='System Role'),
        ),
        migrations.AlterField(
            model_name='adbizroles',
            name='is_system',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is System?'),
        ),
    ]
