# Generated by Django 3.0.5 on 2020-06-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0002_auto_20200613_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdbizRolePrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=32, verbose_name='Module')),
                ('privileges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizWebUIEngine.AdbizPrivileges', verbose_name='Privileges')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizWebUIEngine.AdbizRoles', verbose_name='Role')),
            ],
            options={
                'db_table': 'role_privileges',
            },
        ),
    ]
