# Generated by Django 3.0.5 on 2020-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0003_adbizroleprivileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbizprivileges',
            name='privilege_code',
            field=models.CharField(max_length=32, null=True, verbose_name='Privilege Code'),
        ),
        migrations.AddField(
            model_name='adbizroles',
            name='role_code',
            field=models.CharField(max_length=32, null=True, verbose_name='Role Code'),
        ),
    ]
