# Generated by Django 3.0.5 on 2020-06-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0004_auto_20200614_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbizmenuitems',
            name='parent_menu_id',
        ),
        migrations.RemoveField(
            model_name='adbizmenuitems',
            name='role',
        ),
        migrations.AddField(
            model_name='adbizmenuitems',
            name='menu_code',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Menu Item Code'),
        ),
        migrations.AddField(
            model_name='adbizmenuitems',
            name='menu_display_properties',
            field=models.TextField(null=True, verbose_name='Display Properties'),
        ),
        migrations.AlterField(
            model_name='adbizmenuitems',
            name='display_seq',
            field=models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login_dt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login_attempts',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Login Attempts'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_account',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='User Account (generated)'),
        ),
    ]
