# Generated by Django 3.0.5 on 2020-06-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0005_auto_20200617_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbizmenuitems',
            name='menu_display_properties',
        ),
        migrations.AddField(
            model_name='adbizmenuitems',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adbizmenuitems',
            name='menu_properties',
            field=models.TextField(null=True, verbose_name='Properties'),
        ),
        migrations.AddField(
            model_name='adbizmenuitems',
            name='parent_menu_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adbizmenuitems',
            name='display_seq',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
