# Generated by Django 3.0.5 on 2020-06-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0006_auto_20200617_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdbizMenuRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizWebUIEngine.AdbizMenuItems')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizWebUIEngine.AdbizRoles')),
            ],
            options={
                'db_table': 'menu_roles',
            },
        ),
    ]
