# Generated by Django 3.0.5 on 2020-06-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0007_adbizmenuroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbizuiengine',
            name='tenant_namespace',
            field=models.CharField(editable=False, max_length=8, null=True, verbose_name='Tenant Namespace'),
        ),
    ]
