# Generated by Django 3.0.5 on 2020-06-17 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0008_adbizuiengine_tenant_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_staff_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joining Date'),
        ),
    ]
