# Generated by Django 3.0.5 on 2020-06-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0009_auto_20200617_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_staff_user',
            new_name='is_staff',
        ),
    ]
