# Generated by Django 3.0.5 on 2020-06-17 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('adbizWebUIEngine', '0011_auto_20200617_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdbizUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_account', models.CharField(max_length=255, null=True, unique=True, verbose_name='User Account (generated)')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=64, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='Last Name')),
                ('dob', models.DateField(null=True, verbose_name='Date of birth')),
                ('joined_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joining Date')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_systemuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('login_attempts', models.SmallIntegerField(default=0, editable=False, verbose_name='Login Attempts')),
                ('last_login_dt', models.DateTimeField(editable=False, null=True, verbose_name='Last Login')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated on')),
                ('last_updated_by', models.CharField(max_length=64, verbose_name='Last updated By')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizWebUIEngine.AdbizUIEngine', verbose_name='UI Engine ID (generated)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'adbiz_users',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
