# Generated by Django 3.0.5 on 2020-06-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0012_auto_20200617_1957'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adbizuser',
            table='users',
        ),
    ]
