# Generated by Django 3.0.5 on 2020-07-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0014_auto_20200627_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdbizDashboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=32, verbose_name='Module')),
                ('dashboard_code', models.CharField(max_length=255, verbose_name='Dashboard Code')),
                ('dashboard_class', models.CharField(max_length=32, verbose_name='Dashboard Reference Class')),
                ('dashboard_title', models.CharField(max_length=32, verbose_name='Dashboard Title')),
                ('dashboard_sub_title', models.CharField(max_length=32, verbose_name='Dashboard Sub Title')),
            ],
            options={
                'db_table': 'Dashboards',
                'managed': True,
            },
        ),
    ]
