# Generated by Django 3.0.5 on 2020-04-30 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('country_name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 4, 30, 17, 47, 10, 514056, tzinfo=utc))),
                ('create_by', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=3, unique=True)),
                ('state_name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 4, 30, 17, 47, 10, 514560, tzinfo=utc))),
                ('create_by', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizTestApp.Country')),
            ],
            options={
                'db_table': 'State',
            },
        ),
    ]
