# Generated by Django 3.0.5 on 2020-07-11 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adbizTestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 12, 10, 8, 473341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 12, 10, 8, 473793, tzinfo=utc)),
        ),
    ]
