# Generated by Django 3.0.5 on 2020-07-11 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adbizTestApp', '0002_auto_20200711_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, unique=True)),
                ('last_name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dob', models.DateTimeField(default=datetime.datetime(2020, 7, 11, 12, 22, 58, 92662, tzinfo=utc))),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 12, 22, 58, 91711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 12, 22, 58, 92178, tzinfo=utc)),
        ),
    ]
