# Generated by Django 3.0.5 on 2020-06-27 19:15

import components.core.packages.lookups
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adbizCatalogService', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='dashboardcomponents',
            name='component_sub_type',
            field=models.CharField(choices=[('G', 'Widget - Generic')], default=components.core.packages.lookups.ComponentSubDisplayType['G'], max_length=32, verbose_name='Component Sub Type'),
        ),
        migrations.AddField(
            model_name='dashboardcomponents',
            name='component_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Component Title'),
        ),
        migrations.AddField(
            model_name='dashboardcomponents',
            name='component_tooltip',
            field=models.CharField(max_length=255, null=True, verbose_name='Component Tooltip'),
        ),
        migrations.AddField(
            model_name='dashboards',
            name='dashboard_sub_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Dashboard Sub Title'),
        ),
        migrations.AddField(
            model_name='dashboards',
            name='dashboard_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Dashboard Title'),
        ),

        migrations.AddField(
            model_name='datamodels',
            name='instance_code',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Environment/Instance'),
        ),
        migrations.AlterField(
            model_name='batchlogs',
            name='batch_id',
            field=models.UUIDField(default=uuid.UUID('e45c64dd-bbee-42bc-9022-2b951c86f54b'), verbose_name='Batch Id'),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='dashboard_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Dashboard Name'),
        ),
    ]
