# Generated by Django 3.0.5 on 2020-05-18 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adbizCatalogService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgHierarchyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(editable=False, max_length=64, verbose_name='Customer')),
                ('site_code', models.CharField(editable=False, max_length=64, verbose_name='Site')),
                ('type', models.CharField(max_length=32, verbose_name='Hierarchy Type')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('hierarchy_class_reference', models.CharField(max_length=32, null=True, verbose_name='Hierarchy Class')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='System Based ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Created On')),
                ('last_updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Last Updated On')),
                ('last_updated_by', models.CharField(editable=False, max_length=64, verbose_name='Last Updated By')),
            ],
            options={
                'db_table': 'org_hierarchy_types',
            },
        ),
        migrations.AlterField(
            model_name='aggregatedimensions',
            name='dimension_type',
            field=models.CharField(choices=[('D', 'By Date'), ('V', 'By Value')], max_length=255, verbose_name='Dimension Type'),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='dimension_type',
            field=models.CharField(choices=[('D', 'By Date'), ('V', 'By Value')], max_length=32, verbose_name='Dimension Type'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='entity_sub_type',
            field=models.CharField(choices=[('HO', 'Head Office'), ('DIV', 'Division'), ('WH', 'Warehouse'), ('DC', 'Distribution Center'), ('RO', 'Regional Office'), ('MO', 'Marketing Office'), ('SO', 'Sales Office')], max_length=32, null=True, verbose_name='Entity Sub Type'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='entity_type',
            field=models.CharField(choices=[('LE', 'Legal Entity'), ('BU', 'Business Unit'), ('BR', 'Branch Office')], max_length=32, verbose_name='Entity Type'),
        ),
        migrations.CreateModel(
            name='OrgHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(editable=False, max_length=64, verbose_name='Customer')),
                ('site_code', models.CharField(editable=False, max_length=64, verbose_name='Site')),
                ('hierarchy_name', models.CharField(max_length=32, verbose_name='Hierarchy Type')),
                ('hierarchy_description', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created On')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last Updated On')),
                ('last_updated_by', models.CharField(editable=False, max_length=64, verbose_name='Last Updated By')),
                ('hierarchy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizCatalogService.OrgHierarchyTypes', verbose_name='Hierarchy Type')),
                ('parent_hierarchy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adbizCatalogService.OrgHierarchy')),
            ],
            options={
                'db_table': 'org_hierarchies',
            },
        ),
        migrations.AlterField(
            model_name='catalogs',
            name='hierarchy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizCatalogService.OrgHierarchyTypes', verbose_name='Hierarchy Type'),
        ),
    ]
