# Generated by Django 3.0.5 on 2020-06-09 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adbizCatalogService', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardcomponents',
            old_name='data_filter',
            new_name='data_filters',
        ),
        migrations.RemoveField(
            model_name='dashboardcomponents',
            name='quick_option',
        ),
        migrations.RemoveField(
            model_name='dashboardcomponents',
            name='quick_option_value',
        ),
        migrations.AlterField(
            model_name='batchlogs',
            name='batch_id',
            field=models.UUIDField(default=uuid.UUID('71883119-1d07-42c2-86d7-8c932baf3835'), verbose_name='Batch Id'),
        ),
    ]
