# Generated by Django 3.0.5 on 2020-05-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adbizCatalogService', '0003_entities_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogs',
            name='module',
        ),
    ]
