# Generated by Django 3.0.5 on 2020-07-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adbizWebUIEngine', '0015_adbizdashboards'),
        ('adbizActRbl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActRblDashboards',
            fields=[
                ('adbizdashboards_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adbizWebUIEngine.AdbizDashboards')),
            ],
            options={
                'managed': False,
            },
            bases=('adbizWebUIEngine.adbizdashboards',),
        ),
    ]
