"""
Django settings for adbizWebUI project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from .common.logger import Adbizlogger
from .common.utils import ClsDbConfig
import logging.config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGGING_CONFIG = None
BASE_LOG_FOLDER = "/home/setupadmin/adbiz/logs"

LOG_CONFIG_FILE = os.path.join(BASE_DIR,"adbizWebUI","config","logging.json")
DB_CONFIG_FILE = os.path.join(BASE_DIR,"adbizWebUI","config","db.json")

log = Adbizlogger(BASE_LOG_FOLDER, LOG_CONFIG_FILE)
main = ClsDbConfig(DB_CONFIG_FILE, "main")
actpbl = ClsDbConfig(DB_CONFIG_FILE, "actpbl")
actrbl = ClsDbConfig(DB_CONFIG_FILE, "actrbl")
reco = ClsDbConfig(DB_CONFIG_FILE, "reco")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0$e0iz6e5ulz=0z@h1+d^p*8sy)n%w_4ty(@p_f@3j799b&qfe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adbizActPbl',
    'adbizActRbl',
    'adbizReco',
    'adbizWebUIEngine',
    'chartjs',
    'django_tables2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
SECURE_CONTENT_TYPE_NOSNIFF = True
ROOT_URLCONF = 'adbizWebUI.urls'
#'adbizActPbl/templates/', 'adbizActRbl/templates/', 'adbizReco/templates/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"adbizWebUIEngine","templates"), os.path.join(BASE_DIR,"adbizWebUI","templates"), os.path.join(BASE_DIR,"adbizActRbl","templates"),os.path.join(BASE_DIR,"adbizActPbl","templates"), os.path.join(BASE_DIR,"adbizReco","templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adbizWebUI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases



DATABASE_APPS_MAPPING = {
    'ACTPBL':'ACTPBL',
    'ACTRBL': 'ACTRBL',
    'RECO':'RECO'
}

DATABASES = {
    'default': {
        'ENGINE':main.engine(),
        'USER':main.user(),
        'PASSWORD':main.password(),
        'HOST':main.server(),
        'PORT':main.port(),
        'NAME':main.dbname(),
    },
    'ACTPBL':{
        'ENGINE': actpbl.engine(),
        'USER': actpbl.user(),
        'PASSWORD': actpbl.password(),
        'HOST': actpbl.server(),
        'PORT': actpbl.port(),
        'NAME': actpbl.dbname(),
    },
    'ACTRBL': {
        'ENGINE': actrbl.engine(),
        'USER': actrbl.user(),
        'PASSWORD': actrbl.password(),
        'HOST': actrbl.server(),
        'PORT': actrbl.port(),
        'NAME': actrbl.dbname(),
    },
    'RECO': {
        'ENGINE': reco.engine(),
        'USER': reco.user(),
        'PASSWORD': reco.password(),
        'HOST': reco.server(),
        'PORT': reco.port(),
        'NAME': reco.dbname(),
    }
}

DATABASE_ROUTERS = ['adbizWebUI.routers.dbrouter.AdbizDbRouter']

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'adbizWebUIEngine.AdbizUser'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'root')

STATICFILES_DIRS = [
        os.path.join(BASE_DIR, '/home/setupadmin/adbiz/components/Web/ui/veltrix/'),
]
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/adbizUI/adbizActRbl/home'
LOGOUT_REDIRECT_URL = '/adbizUI/'

