# Generated by Django 3.0.5 on 2020-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizProductEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseengineactivations',
            name='site',
            field=models.CharField(max_length=64, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='licenseenvactivations',
            name='site',
            field=models.CharField(max_length=64, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='licensemoduleactivations',
            name='site',
            field=models.CharField(max_length=64, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='licensesiteactivations',
            name='site',
            field=models.CharField(max_length=64, verbose_name='Site'),
        ),
    ]
