# Generated by Django 3.0.5 on 2020-05-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizCoreEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreengine',
            name='core_engine_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Core Engine Code (generated)'),
        ),
        migrations.AlterField(
            model_name='environments',
            name='environment_code',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Environment ID (generated)'),
        ),
        migrations.AlterField(
            model_name='processingengines',
            name='processing_engine_code',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Processing Engine Code (generated)'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_code',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Site ID (generated)'),
        ),
    ]
