# Generated by Django 3.0.5 on 2020-06-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbizCoreEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingengines',
            name='module',
            field=models.CharField(default='ALL', max_length=32, null=True, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='licensinginfo',
            name='active_engines',
            field=models.CharField(choices=[('PE', 'Product Engine'), ('CE', 'Core Engine'), ('EE', 'ETL Engine'), ('IO', 'IO Engine'), ('UI', 'WEB UI ENGINE'), ('CS', 'Catalog Service')], max_length=255, verbose_name='Engines'),
        ),
        migrations.AlterField(
            model_name='processingengines',
            name='processing_engine_type',
            field=models.CharField(choices=[('PE', 'Product Engine'), ('CE', 'Core Engine'), ('EE', 'ETL Engine'), ('IO', 'IO Engine'), ('UI', 'WEB UI ENGINE'), ('CS', 'Catalog Service')], max_length=32, verbose_name='Processing Engine'),
        ),
    ]
