# Generated by Django 3.0.5 on 2020-04-25 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_code', models.CharField(max_length=6, unique=True)),
                ('registration_number', models.CharField(max_length=32, unique=True)),
                ('registered_dt', models.DateTimeField(null=True)),
                ('country', models.CharField(max_length=3)),
                ('state', models.CharField(max_length=3, null=True)),
                ('category', models.CharField(max_length=32, null=True)),
                ('sub_category', models.CharField(max_length=32, null=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('website_url', models.URLField(max_length=128, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isActivated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='ProductEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_instance_id', models.CharField(max_length=255, unique=True, verbose_name='Product Instance ID')),
                ('root_namespace', models.CharField(max_length=6, verbose_name='Namespace')),
                ('registered_to', models.CharField(max_length=64)),
                ('activation_file_location', models.CharField(max_length=128)),
                ('engine_id', models.CharField(max_length=64)),
                ('activation_key', models.CharField(max_length=255)),
                ('activation_dt', models.DateTimeField(editable=False)),
                ('host_name', models.CharField(editable=False, max_length=128)),
                ('host_ip_address', models.GenericIPAddressField()),
                ('os_release', models.CharField(max_length=32, null=True)),
                ('release_info', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_engine',
            },
        ),
    ]
