# Generated by Django 3.0.5 on 2020-06-04 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_engine_code', models.CharField(editable=False, max_length=255, verbose_name='Core Engine Code')),
                ('tenant_code', models.CharField(editable=False, max_length=255, verbose_name='Tenant')),
                ('site_code', models.CharField(editable=False, max_length=255, verbose_name='Site')),
                ('instance_code', models.CharField(editable=False, max_length=255, verbose_name='Environment/Instance')),
                ('module', models.CharField(editable=False, max_length=32, verbose_name='Module')),
                ('storage_engine_class', models.CharField(editable=False, max_length=32, verbose_name='Storage Engine Class')),
                ('data_lake_type', models.CharField(editable=False, max_length=255, verbose_name='Data Lake Type')),
                ('data_lake_sub_type', models.CharField(editable=False, max_length=255, verbose_name='Data Lake Sub Type')),
                ('data_lake_code', models.CharField(editable=False, max_length=255, verbose_name='Data Lake Code')),
                ('data_lake_description', models.TextField(editable=False, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('is_primary', models.BooleanField(default=True, editable=False, verbose_name='Is Primary Storage?')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created On')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last Updated On')),
                ('last_updated_by', models.CharField(editable=False, max_length=64, verbose_name='Last Updated By')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineAPICalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_engine_code', models.CharField(max_length=255, unique=True, verbose_name='IO Engine Code (generated)')),
                ('tenant_code', models.CharField(max_length=255, verbose_name='Tenant')),
                ('site_code', models.CharField(editable=False, max_length=255, verbose_name='Site')),
                ('instance_code', models.CharField(editable=False, max_length=255, verbose_name='Environment/Instance')),
                ('engine_mode', models.CharField(editable=False, max_length=32, verbose_name='IO Engine Mode')),
                ('setup_mode', models.BooleanField(default=False, verbose_name='Setup Mode ?')),
                ('module', models.CharField(default='ALL', editable=False, max_length=32, verbose_name='Module')),
                ('core_engine_code', models.CharField(editable=False, max_length=255, verbose_name='Core Engine Code')),
                ('catalog_engine_code', models.CharField(editable=False, max_length=255, verbose_name='Catalog Engine Code')),
                ('core_engine_url', models.CharField(editable=False, max_length=255, verbose_name='Catalog Engine base URL')),
                ('core_engine_api_key', models.CharField(editable=False, max_length=255, verbose_name='Catalog Engine API Key')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IOEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_engine_code', models.CharField(max_length=255, unique=True, verbose_name='IO Engine Code (generated)')),
                ('core_engine_code', models.CharField(editable=False, max_length=255, verbose_name='Core Engine Code')),
                ('catalog_engine_code', models.CharField(editable=False, max_length=255, verbose_name='Catalog Engine Code')),
                ('tenant_code', models.CharField(max_length=255, verbose_name='Tenant')),
                ('site_code', models.CharField(editable=False, max_length=255, verbose_name='Site')),
                ('instance_code', models.CharField(editable=False, max_length=255, verbose_name='Environment/Instance')),
                ('module', models.CharField(default='ALL', editable=False, max_length=32, verbose_name='Module')),
                ('activation_file_location', models.CharField(max_length=255, verbose_name='Activation File Location')),
                ('activation_key', models.CharField(editable=False, max_length=255, verbose_name=' Activation Key (generated)')),
                ('activation_dt', models.DateTimeField(verbose_name='Activation Date Time')),
                ('host_name', models.CharField(max_length=128, verbose_name='Host Name')),
                ('host_ip_address', models.GenericIPAddressField(verbose_name='Host IP Address')),
                ('os_release', models.CharField(max_length=32, null=True, verbose_name='OS Release Version')),
                ('release_info', models.CharField(max_length=255, null=True, verbose_name='Version Details')),
                ('validity_start_date', models.DateTimeField(null=True, verbose_name='Validity Start Date')),
                ('validity_end_date', models.DateTimeField(null=True, verbose_name='Validity End Date')),
                ('engine_properties', models.TextField(editable=False, verbose_name='Engine Properties')),
                ('core_engine_details', models.TextField(editable=False, verbose_name='Core Engine Details')),
                ('catalog_engine_details', models.TextField(editable=False, verbose_name='Catalog Engine Details')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Activated ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created On')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last Updated On')),
                ('last_updated_by', models.CharField(editable=False, max_length=64, verbose_name='Last Updated By')),
            ],
            options={
                'db_table': 'engine_metadata',
            },
        ),
        migrations.CreateModel(
            name='IOEngineActivations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_engine_code', models.CharField(editable=False, max_length=255, verbose_name='Core Engine Code')),
                ('catalog_engine_code', models.CharField(editable=False, max_length=255, verbose_name='Catalog Engine Code')),
                ('tenant_code', models.CharField(max_length=255, verbose_name='Tenant')),
                ('site_code', models.CharField(editable=False, max_length=255, verbose_name='Site')),
                ('instance_code', models.CharField(editable=False, max_length=255, verbose_name='Environment/Instance')),
                ('activation_file_location', models.CharField(max_length=255, verbose_name='Activation File Location')),
                ('activation_key', models.CharField(editable=False, max_length=255, verbose_name='Activation Key')),
                ('validity_start_date', models.DateTimeField(editable=False, null=True, verbose_name='Validity Start Date')),
                ('validity_end_date', models.DateTimeField(editable=False, null=True, verbose_name='Validity End Date')),
                ('activation_dt', models.DateTimeField(editable=False, verbose_name='Activation Date Time')),
                ('deactivation_dt', models.DateTimeField(editable=False, null=True, verbose_name='Deactivation Date Time')),
                ('catalog_engine_details', models.TextField(null=True, verbose_name='Catalog Engine Details')),
                ('core_engine_details', models.TextField(null=True, verbose_name='Core Engine Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created On')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last Updated On')),
                ('last_updated_by', models.CharField(editable=False, max_length=64, verbose_name='Last Updated By')),
                ('io_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbizIOEngine.IOEngine', verbose_name='IO Engine')),
            ],
            options={
                'db_table': 'engine_activations',
            },
        ),
    ]
